# syntax=docker.io/docker/dockerfile:1

FROM node:20-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json package-lock.json* ./
COPY prisma ./prisma/

RUN npm ci

CMD ["npx", "prisma", "migrate", "deploy"]
