{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jotlin.secretName" . }}
  labels:
    {{- include "jotlin.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secretEnv.DATABASE_URL | quote }}
  OPENAI_API_KEY: {{ .Values.secretEnv.OPENAI_API_KEY | quote }}
  TAVILY_API_KEY: {{ .Values.secretEnv.TAVILY_API_KEY | quote }}
  GITHUB_CLIENT_ID: {{ .Values.secretEnv.GITHUB_CLIENT_ID | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secretEnv.GITHUB_CLIENT_SECRET | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secretEnv.GOOGLE_CLIENT_ID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secretEnv.GOOGLE_CLIENT_SECRET | quote }}
  JWT_SECRET: {{ .Values.secretEnv.JWT_SECRET | quote }}
  SEALOS_JWT_SECRET: {{ .Values.secretEnv.SEALOS_JWT_SECRET | quote }}
  S3_ACCESS_KEY: {{ .Values.secretEnv.S3_ACCESS_KEY | quote }}
  S3_SECRET_KEY: {{ .Values.secretEnv.S3_SECRET_KEY | quote }}
{{- end }}
